### ISSUE TITLE
Suggestion: Adding 'Read more'

### ISSUE THREAD

**Issue by andrewhuanggg** [ossd-s24/tchen0125-weekly#1]
In your blog posts, you should add this separator: `<!--more-->` exactly where you want 'READ MORE' to appear on the blog post. Usually this is added after the first chunk of text, so that if the reader is interested in knowing more after an initial read, they can click 'READ MORE' and it will expand to show the entire blog post. For example, if you wanted the 'READ MORE' to appear in your Week 4 blog post, you could simply add the separator after your first paragraph like so: 

Therefore, I found my work with my team members very smooth and innovative. 
`<!--more-->`

**Comment by tchen0125** [comment]
Thank you!
